In [1]:
import requests
from bs4 import BeautifulSoup

In [230]:
response = requests.get(url='https://www.baseball-reference.com/boxes/ARI/ARI201403220.shtml')

In [232]:
data_html = response.text

In [233]:
with open('./data/data.html', 'w') as  outfile:
    outfile.write(data_html)

In [29]:
bs.tbody.tr.find_all("td")[1].get_text()

'Los Angeles Dodgers'

In [30]:
r1 = requests.get(url='https://www.baseball-reference.com/boxes/ANA/ANA201403310.shtml')
data_sea_ana_20230331 = r1.text

In [31]:
bs2 = BeautifulSoup(data_sea_ana_20230331)

In [33]:
pitch_team = bs2.tbody.tr.find_all("td")[1].get_text()

In [47]:
team_name = pitch_team.replace(' ','')

In [42]:
team_name

'SeattleMariners'

In [198]:
import pandas as pd

In [208]:
import re

In [236]:
t = re.findall(r'div class=\"table_container\"[\s\S]+?</table>', data_html)

In [237]:
len(t)

6

In [241]:
t[3]

'div class="table_container" id="div_ArizonaDiamondbackspitching">\n    \n    <table class="sortable stats_table min_width shade_zero" id="ArizonaDiamondbackspitching" data-cols-to-freeze=",1">\n    <caption>Arizona Diamondbacks Table</caption>\n    \n\n   <colgroup><col><col><col><col><col><col><col><col><col><col><col><col><col><col><col><col><col><col><col><col><col><col><col><col><col><col><col></colgroup>\n   <thead>      \n      <tr>\n         <th aria-label="Pitching" data-stat="player" scope="col" class=" poptip sort_default_asc show_partial_when_sorting left" data-tip="&lt;strong&gt;Player Name&lt;/strong&gt;&lt;br&gt;&lt;strong&gt;Bold&lt;/strong&gt; can mean player is active for this team&lt;br&gt;or player has appeared in the majors&lt;br&gt;* means LHP or LHB,&lt;br&gt;# means switch hitter,&lt;br&gt;+ can mean HOFer." >Pitching</th>\n         <th aria-label="Innings Pitched" data-stat="IP" scope="col" class=" poptip center" data-tip="Innings Pitched" data-filter="1" data-name="Innings Pitched" >IP</th>\n         <th aria-label="Hits" data-stat="H" scope="col" class=" poptip center" data-tip="Hits/Hits Allowed" >H</th>\n         <th aria-label="Runs Scored" data-stat="R" scope="col" class=" poptip center" data-tip="Runs Scored/Allowed" >R</th>\n         <th aria-label="Earned Runs" data-stat="ER" scope="col" class=" poptip center" data-tip="Earned Runs Allowed" >ER</th>\n         <th aria-label="Bases on Balls" data-stat="BB" scope="col" class=" poptip center" data-tip="Bases on Balls/Walks" >BB</th>\n         <th aria-label="Strikeouts" data-stat="SO" scope="col" class=" poptip center" data-tip="Strikeouts" >SO</th>\n         <th aria-label="Home Runs" data-stat="HR" scope="col" class=" poptip center" data-tip="Home Runs Hit/Allowed" >HR</th>\n         <th aria-label="Earned Run Average" data-stat="earned_run_avg" scope="col" class=" poptip sort_default_asc hide_non_quals center" data-tip="&lt;strong&gt;9 * ER / IP&lt;/strong&gt;&lt;br&gt;For recent years, leaders need 1 IP&lt;br&gt;per team game played.&lt;br&gt;Bold indicates lowest ERA using current stats&lt;br&gt;&lt;span class=glimmer&gt;Gold&lt;/span&gt; means awarded ERA title at end of year." data-filter="1" data-name="Earned Run Average" >ERA</th>\n         <th aria-label="Batters Faced" data-stat="batters_faced" scope="col" class=" poptip center" data-tip="Batters Faced" >BF</th>\n         <th aria-label="Pit" data-stat="pitches" scope="col" class=" poptip center" data-tip="Number of pitches in the PA." >Pit</th>\n         <th aria-label="Str" data-stat="strikes_total" scope="col" class=" poptip center" data-tip="&lt;strong&gt;Strikes&lt;/strong&gt;&lt;br&gt;Includes both pitches in the zone and those swung at out of the zone." >Str</th>\n         <th aria-label="Ctct" data-stat="strikes_contact" scope="col" class=" poptip center" data-tip="&lt;strong&gt;Strikes by Contact&lt;/strong&gt;&lt;br&gt;Strikes from foul balls or balls put into play." >Ctct</th>\n         <th aria-label="StS" data-stat="strikes_swinging" scope="col" class=" poptip center" data-tip="&lt;strong&gt;Strikes Swinging&lt;/strong&gt;&lt;br&gt;Strikes due to a swing and a miss." >StS</th>\n         <th aria-label="StL" data-stat="strikes_looking" scope="col" class=" poptip center" data-tip="&lt;strong&gt;Strikes Looking&lt;/strong&gt;&lt;br&gt;Strikes called by the umpire." >StL</th>\n         <th aria-label="GB" data-stat="inplay_gb_total" scope="col" class=" poptip center" data-tip="&lt;strong&gt;Ground Balls&lt;/strong&gt;&lt;br&gt;Includes bunts and all other ground balls." >GB</th>\n         <th aria-label="FB" data-stat="inplay_fb_total" scope="col" class=" poptip center" data-tip="&lt;strong&gt;Fly Balls&lt;/strong&gt;&lt;br&gt;Includes Fly Balls, Line Drives, and Pop-Ups." >FB</th>\n         <th aria-label="LD" data-stat="inplay_ld" scope="col" class=" poptip center" data-tip="&lt;strong&gt;Line Drives&lt;/strong&gt;&lt;br&gt;These are double-counted in Fly Balls as well." >LD</th>\n         <th aria-label="Unk" data-stat="inplay_unk" scope="col" class=" poptip center" data-tip="&lt;strong&gt;Unknown batted ball type&lt;/strong&gt;&lt;br&gt;A ball in play for which we don&amp;#x2019;t know the type." >Unk</th>\n         <th aria-label="Game Score" data-stat="game_score" scope="col" class=" poptip center" data-tip="&lt;strong&gt;Game Score&lt;/strong&gt;&lt;br&gt;Developed by Bill James&lt;br&gt;1. Start with 50 points.&lt;br&gt; 2. Add 1 point for each out recorded, so 3 points for every complete inning pitched.&lt;br&gt; 3. Add 2 points for each inning completed after the 4th.&lt;br&gt; 4. Add 1 point for each strikeout.&lt;br&gt; 5. Subtract 2 points for each hit allowed.&lt;br&gt; 6. Subtract 4 points for each earned run allowed.&lt;br&gt; 7. Subtract 2 points for each unearned run allowed.&lt;br&gt; 8. Subtract 1 point for each walk.&lt;br&gt;" >GSc</th>\n         <th aria-label="IR" data-stat="inherited_runners" scope="col" class=" poptip center" data-tip="&lt;strong&gt;Inherited Runners&lt;/strong&gt;&lt;br&gt;Number of runners on base when pitcher entered the game." >IR</th>\n         <th aria-label="IS" data-stat="inherited_score" scope="col" class=" poptip center" data-tip="&lt;strong&gt;Inherited Score&lt;/strong&gt;&lt;br&gt;Number or percentage of runners on base when pitcher entered the game who subsequently scored.&lt;br&gt;These runners show up in the previous pitcher&amp;#x2019;s ERA." >IS</th>\n         <th aria-label="Win Probability Added (WPA)" data-stat="wpa_def" scope="col" class=" poptip center" data-tip="&lt;strong&gt;Win Probability Added by Pitcher&lt;/strong&gt;&lt;br&gt;Given average teams, this is the change in probability&lt;br&gt;A change of +/- 1 would indicate one win added or lost." data-filter="1" data-name="Win Probability Added (WPA)" >WPA</th>\n         <th aria-label="aLI" data-stat="leverage_index_avg" scope="col" class=" poptip hide_non_quals center" data-tip="&lt;strong&gt;Average Leverage Index&lt;/strong&gt;&lt;br&gt;The average pressure the pitcher or batter saw in this game or season.&lt;br&gt;1.0 is average pressure, below 1.0 is low pressure and above 1.0 is high pressure." data-filter="1" data-name="aLI" >aLI</th>\n         <th aria-label="Championship WPA (cWPA)" data-stat="cwpa_def" scope="col" class=" poptip center" data-tip="&lt;strong&gt;Championship Win Probability Added by Pitcher&lt;/strong&gt;&lt;br&gt;Given average teams, this is the change in probability, displayed in percentage points.&lt;br&gt;A change of +/- 100% would indicate one world series win added or lost." data-filter="1" data-name="Championship WPA (cWPA)" >cWPA</th>\n         <th aria-label="acLI" data-stat="cli_avg" scope="col" class=" poptip hide_non_quals center" data-tip="&lt;strong&gt;Average Championship Leverage Index&lt;/strong&gt;&lt;br&gt;The average pressure the pitcher or batter saw in this game or season.&lt;br&gt;1.0 is average pressure, below 1.0 is low pressure and above 1.0 is high pressure." data-filter="1" data-name="acLI" >acLI</th>\n         <th aria-label="Base-Out Runs Saved (RE24)" data-stat="re24_def" scope="col" class=" poptip center" data-tip="&lt;strong&gt;Base-Out Runs Saved&lt;/strong&gt;&lt;br&gt;Given the bases occupied/out situation, how many runs did the pitcher&lt;br&gt;save in the resulting play. Compared to average, so 0 is average, and&lt;br&gt;above 0 is better than average" data-filter="1" data-name="Base-Out Runs Saved (RE24)" >RE24</th>\n      </tr>\n      </thead>\n<tbody><tr ><th scope="row" class="left " data-append-csv="mileywa01" data-stat="player" csk="0" ><a href="/players/m/mileywa01.shtml">Wade Miley</a>, L (0-1)</th><td class="right endpoint" data-endpoint="/tools/pe.cgi?html=1&game-id=ARI201403220-mileywa01" data-stat="IP" > 5 </td><td class="right " data-stat="H" >3</td><td class="right " data-stat="R" >3</td><td class="right " data-stat="ER" >3</td><td class="right " data-stat="BB" >2</td><td class="right " data-stat="SO" >8</td><td class="right " data-stat="HR" >1</td><td class="right " data-stat="earned_run_avg" >5.40</td><td class="right " data-stat="batters_faced" >22</td><td class="right " data-stat="pitches" >83</td><td class="right " data-stat="strikes_total" >54</td><td class="right " data-stat="strikes_contact" >28</td><td class="right " data-stat="strikes_swinging" >11</td><td class="right " data-stat="strikes_looking" >15</td><td class="right " data-stat="inplay_gb_total" >6</td><td class="right " data-stat="inplay_fb_total" >7</td><td class="right " data-stat="inplay_ld" >3</td><td class="right iz" data-stat="inplay_unk" >0</td><td class="right " data-stat="game_score" >55</td><td class="right iz" data-stat="inherited_runners" ></td><td class="right iz" data-stat="inherited_score" ></td><td class="right " data-stat="wpa_def" >-0.129</td><td class="right " data-stat="leverage_index_avg" > 0.83</td><td class="right " data-stat="cwpa_def" >-0.08%</td><td class="right " data-stat="cli_avg" > 0.90</td><td class="right " data-stat="re24_def" > -0.7</td></tr>\n<tr ><th scope="row" class="left " data-append-csv="harriwi10" data-stat="player" csk="1" ><a href="/players/h/harriwi10.shtml">Will Harris</a></th><td class="right endpoint" data-endpoint="/tools/pe.cgi?html=1&game-id=ARI201403220-harriwi10" data-stat="IP" > 2 </td><td class="right " data-stat="H" >1</td><td class="right iz" data-stat="R" >0</td><td class="right iz" data-stat="ER" >0</td><td class="right iz" data-stat="BB" >0</td><td class="right " data-stat="SO" >3</td><td class="right iz" data-stat="HR" >0</td><td class="right iz" data-stat="earned_run_avg" >0.00</td><td class="right " data-stat="batters_faced" >6</td><td class="right " data-stat="pitches" >30</td><td class="right " data-stat="strikes_total" >18</td><td class="right " data-stat="strikes_contact" >8</td><td class="right " data-stat="strikes_swinging" >4</td><td class="right " data-stat="strikes_looking" >6</td><td class="right iz" data-stat="inplay_gb_total" >0</td><td class="right " data-stat="inplay_fb_total" >3</td><td class="right " data-stat="inplay_ld" >2</td><td class="right iz" data-stat="inplay_unk" >0</td><td class="right iz" data-stat="game_score" ></td><td class="right iz" data-stat="inherited_runners" >0</td><td class="right iz" data-stat="inherited_score" >0</td><td class="right " data-stat="wpa_def" >0.050</td><td class="right " data-stat="leverage_index_avg" > 0.34</td><td class="right " data-stat="cwpa_def" > 0.03%</td><td class="right " data-stat="cli_avg" > 0.37</td><td class="right " data-stat="re24_def" > 0.9</td></tr>\n<tr ><th scope="row" class="left " data-append-csv="zieglbr01" data-stat="player" csk="2" ><a href="/players/z/zieglbr01.shtml">Brad Ziegler</a></th><td class="right endpoint" data-endpoint="/tools/pe.cgi?html=1&game-id=ARI201403220-zieglbr01" data-stat="IP" > 1 </td><td class="right " data-stat="H" >1</td><td class="right iz" data-stat="R" >0</td><td class="right iz" data-stat="ER" >0</td><td class="right " data-stat="BB" >1</td><td class="right iz" data-stat="SO" >0</td><td class="right iz" data-stat="HR" >0</td><td class="right iz" data-stat="earned_run_avg" >0.00</td><td class="right " data-stat="batters_faced" >5</td><td class="right " data-stat="pitches" >15</td><td class="right " data-stat="strikes_total" >8</td><td class="right " data-stat="strikes_contact" >5</td><td class="right " data-stat="strikes_swinging" >1</td><td class="right " data-stat="strikes_looking" >2</td><td class="right " data-stat="inplay_gb_total" >3</td><td class="right " data-stat="inplay_fb_total" >1</td><td class="right " data-stat="inplay_ld" >1</td><td class="right iz" data-stat="inplay_unk" >0</td><td class="right iz" data-stat="game_score" ></td><td class="right iz" data-stat="inherited_runners" >0</td><td class="right iz" data-stat="inherited_score" >0</td><td class="right " data-stat="wpa_def" >0.024</td><td class="right " data-stat="leverage_index_avg" > 0.49</td><td class="right " data-stat="cwpa_def" > 0.01%</td><td class="right " data-stat="cli_avg" > 0.53</td><td class="right " data-stat="re24_def" > 0.5</td></tr>\n<tr ><th scope="row" class="left " data-append-csv="perezol01" data-stat="player" csk="3" ><a href="/players/p/perezol01.shtml">Oliver Perez</a></th><td class="right endpoint" data-endpoint="/tools/pe.cgi?html=1&game-id=ARI201403220-perezol01" data-stat="IP" > 0.1</td><td class="right iz" data-stat="H" >0</td><td class="right iz" data-stat="R" >0</td><td class="right iz" data-stat="ER" >0</td><td class="right iz" data-stat="BB" >0</td><td class="right iz" data-stat="SO" >0</td><td class="right iz" data-stat="HR" >0</td><td class="right iz" data-stat="earned_run_avg" >0.00</td><td class="right " data-stat="batters_faced" >2</td><td class="right " data-stat="pitches" >5</td><td class="right " data-stat="strikes_total" >2</td><td class="right " data-stat="strikes_contact" >2</td><td class="right iz" data-stat="strikes_swinging" >0</td><td class="right iz" data-stat="strikes_looking" >0</td><td class="right " data-stat="inplay_gb_total" >1</td><td class="right iz" data-stat="inplay_fb_total" >0</td><td class="right iz" data-stat="inplay_ld" >0</td><td class="right iz" data-stat="inplay_unk" >0</td><td class="right iz" data-stat="game_score" ></td><td class="right iz" data-stat="inherited_runners" >0</td><td class="right iz" data-stat="inherited_score" >0</td><td class="right " data-stat="wpa_def" >0.000</td><td class="right " data-stat="leverage_index_avg" > 0.23</td><td class="right " data-stat="cwpa_def" > 0.00%</td><td class="right " data-stat="cli_avg" > 0.26</td><td class="right " data-stat="re24_def" > -0.0</td></tr>\n<tr ><th scope="row" class="left " data-append-csv="putzjj01" data-stat="player" csk="4" ><a href="/players/p/putzjj01.shtml">J.J. Putz</a></th><td class="right endpoint" data-endpoint="/tools/pe.cgi?html=1&game-id=ARI201403220-putzjj01" data-stat="IP" > 0.2</td><td class="right iz" data-stat="H" >0</td><td class="right iz" data-stat="R" >0</td><td class="right iz" data-stat="ER" >0</td><td class="right iz" data-stat="BB" >0</td><td class="right iz" data-stat="SO" >0</td><td class="right iz" data-stat="HR" >0</td><td class="right iz" data-stat="earned_run_avg" >0.00</td><td class="right " data-stat="batters_faced" >2</td><td class="right " data-stat="pitches" >3</td><td class="right " data-stat="strikes_total" >3</td><td class="right " data-stat="strikes_contact" >3</td><td class="right iz" data-stat="strikes_swinging" >0</td><td class="right iz" data-stat="strikes_looking" >0</td><td class="right iz" data-stat="inplay_gb_total" >0</td><td class="right " data-stat="inplay_fb_total" >2</td><td class="right " data-stat="inplay_ld" >1</td><td class="right iz" data-stat="inplay_unk" >0</td><td class="right iz" data-stat="game_score" ></td><td class="right " data-stat="inherited_runners" >1</td><td class="right iz" data-stat="inherited_score" >0</td><td class="right " data-stat="wpa_def" >0.015</td><td class="right " data-stat="leverage_index_avg" > 0.29</td><td class="right " data-stat="cwpa_def" > 0.01%</td><td class="right " data-stat="cli_avg" > 0.32</td><td class="right " data-stat="re24_def" > 0.5</td></tr>\n</tbody><tfoot><tr ><th scope="row" class="left " data-stat="player" >Team Totals</th><td class="right " data-stat="IP" > 9 </td><td class="right " data-stat="H" >5</td><td class="right " data-stat="R" >3</td><td class="right " data-stat="ER" >3</td><td class="right " data-stat="BB" >3</td><td class="right " data-stat="SO" >11</td><td class="right " data-stat="HR" >1</td><td class="right " data-stat="earned_run_avg" > 3.00</td><td class="right " data-stat="batters_faced" >37</td><td class="right " data-stat="pitches" >136</td><td class="right " data-stat="strikes_total" >85</td><td class="right " data-stat="strikes_contact" >46</td><td class="right " data-stat="strikes_swinging" >16</td><td class="right " data-stat="strikes_looking" >23</td><td class="right " data-stat="inplay_gb_total" >10</td><td class="right " data-stat="inplay_fb_total" >13</td><td class="right " data-stat="inplay_ld" >7</td><td class="right iz" data-stat="inplay_unk" >0</td><td class="right " data-stat="game_score" >55</td><td class="right " data-stat="inherited_runners" >1</td><td class="right iz" data-stat="inherited_score" >0</td><td class="right " data-stat="wpa_def" >-0.040</td><td class="right " data-stat="leverage_index_avg" > 0.65</td><td class="right " data-stat="cwpa_def" >-0.03%</td><td class="right " data-stat="cli_avg" > 0.70</td><td class="right " data-stat="re24_def" > 1.1</td></tr>\n\n   </tfoot>\n\n</table>'

In [245]:
df = pd.read_html(t[3])

In [246]:
df

[              Pitching   IP  H  R  ER  BB  SO  HR  ERA  BF  ...  LD  Unk
 0  Wade Miley, L (0-1)  5.0  3  3   3   2   8   1  5.4  22  ...   3    0  \
 1          Will Harris  2.0  1  0   0   0   3   0  0.0   6  ...   2    0
 2         Brad Ziegler  1.0  1  0   0   1   0   0  0.0   5  ...   1    0
 3         Oliver Perez  0.1  0  0   0   0   0   0  0.0   2  ...   0    0
 4            J.J. Putz  0.2  0  0   0   0   0   0  0.0   2  ...   1    0
 5          Team Totals  9.0  5  3   3   3  11   1  3.0  37  ...   7    0

     GSc   IR   IS    WPA   aLI    cWPA  acLI  RE24
 0  55.0  NaN  NaN -0.129  0.83  -0.08%  0.90  -0.7
 1   NaN  0.0  0.0  0.050  0.34   0.03%  0.37   0.9
 2   NaN  0.0  0.0  0.024  0.49   0.01%  0.53   0.5
 3   NaN  0.0  0.0  0.000  0.23   0.00%  0.26  -0.0
 4   NaN  1.0  0.0  0.015  0.29   0.01%  0.32   0.5
 5  55.0  1.0  0.0 -0.040  0.65  -0.03%  0.70   1.1

 [6 rows x 27 columns]]

In [270]:
import requests
from bs4 import BeautifulSoup
import re
import pandas as pd

def get_html(date, team, opp) -> str:
    formatted_date = date.replace('-','')
    url = f'https://www.baseball-reference.com/boxes/{team}/{team}{formatted_date}0.shtml'
    response = requests.get(url=url)
    if response.status_code == 400:
        url = f'https://www.baseball-reference.com/boxes/{opp}/{opp}{formatted_date}0.shtml'
        response = requests.get(url=url)
    data_html = response.text
    return data_html

def format_team_name(soup) -> str:
    pitch_team = soup.tbody.tr.find_all("td")[1].get_text()
    team_name = pitch_team.replace(' ','')
    return team_name

def get_pitching_table(data_html, team_name_re) -> pd.DataFrame:
    t = re.findall(f'div class=\"table_container\" id=\"div_{team_name_re}[\s\S]+?</table>', data_html)
    df = pd.read_html(t[1])
    return df

def team_name_lookup(team_code) -> str:
    lookup = {
        'ARI':'Arizona Diamondbacks'
    }
    team_name = lookup[team_code]
    team_name.replace(' ','')
    return team_name

#data_html = get_html('2014-03-22', 'LAD')

In [264]:
data_html = get_html('2014-03-22','ARI', 'LAD')

In [256]:
soup = BeautifulSoup(data_html)

In [272]:
ptable = get_pitching_table(data_html, 'ArizonaDiamondbacks')

In [276]:
ptable[0]

,Pitching,IP,H,R,ER,BB,SO,HR,ERA,BF,...,LD,Unk,GSc,IR,IS,WPA,aLI,cWPA,acLI,RE24
0,"Wade Miley, L (0-1)",5.0,3,3,3,2,8,1,5.4,22,...,3,0,55.0,NaN,NaN,-0.129,0.83,-0.08%,0.90,-0.7
1,Will Harris,2.0,1,0,0,0,3,0,0.0,6,...,2,0,NaN,0.0,0.0,0.050,0.34,0.03%,0.37,0.9
2,Brad Ziegler,1.0,1,0,0,1,0,0,0.0,5,...,1,0,NaN,0.0,0.0,0.024,0.49,0.01%,0.53,0.5
3,Oliver Perez,0.1,0,0,0,0,0,0,0.0,2,...,0,0,NaN,0.0,0.0,0.000,0.23,0.00%,0.26,-0.0
4,J.J. Putz,0.2,0,0,0,0,0,0,0.0,2,...,1,0,NaN,1.0,0.0,0.015,0.29,0.01%,0.32,0.5
5,Team Totals,9.0,5,3,3,3,11,1,3.0,37,...,7,0,55.0,1.0,0.0,-0.040,0.65,-0.03%,0.70,1.1

In [283]:
ptable[0].columns.values

array(['Pitching', 'IP', 'H', 'R', 'ER', 'BB', 'SO', 'HR', 'ERA', 'BF',
       'Pit', 'Str', 'Ctct', 'StS', 'StL', 'GB', 'FB', 'LD', 'Unk', 'GSc',
       'IR', 'IS', 'WPA', 'aLI', 'cWPA', 'acLI', 'RE24'], dtype=object)

In [303]:
mylist = list(df[0].iloc[0])

In [306]:
metadata = ['2014-03-22', 'LAD', 'ARI']
newlist = metadata + mylist

In [307]:
newlist

['2014-03-22',
 'LAD',
 'ARI',
 'Wade Miley, L (0-1)',
 5.0,
 3,
 3,
 3,
 2,
 8,
 1,
 5.4,
 22,
 83,
 54,
 28,
 11,
 15,
 6,
 7,
 3,
 0,
 55.0,
 nan,
 nan,
 -0.129,
 0.83,
 '-0.08%',
 0.9,
 -0.7]

In [309]:
import csv

In [315]:
with open('./data/game_log_test.csv', 'r') as infile:
    player_games = []
    game_log_reader = csv.reader(infile)
    for row in game_log_reader:
        player_games.append(row)

In [316]:
player_games[0]

['1',
 'A.J. Ellis\\ellisaj01',
 '2014-03-22',
 'LAD',
 'ARI',
 '4',
 '2',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '1',
 '1',
 '-0.024',
 '0.061',
 '0.62',
 '8',
 'C']

In [317]:
with open('./data/xwalk_name_code.csv', 'r') as infile:
    xwalk = infile.read()

In [320]:
xwalk_list = xwalk.split('\n')

In [325]:
xwalk_list[0]

'\ufeff ARI,Arizona Diamondbacks '

In [340]:
xwalk_list2 = [x.split(',') for x in xwalk_list]

In [341]:
xwalk_list2.pop(0)

['\ufeff ARI', 'Arizona Diamondbacks ']

In [342]:
xwalk_list2.insert(0,[' ARI', 'Arizona Diamondbacks'])

In [345]:
xwalk_list3 = [[x[0].strip(),x[1].strip()] for x in xwalk_list2]

In [346]:
xwalk_list3

[['ARI', 'Arizona Diamondbacks'],
 ['ATL', 'Atlanta Braves'],
 ['BAL', 'Baltimore Orioles'],
 ['BOS', 'Boston Red Sox'],
 ['CHC', 'Chicago Cubs'],
 ['CHW', 'Chicago White Sox'],
 ['CHW', 'Chicago White Sox'],
 ['CIN', 'Cincinnati Reds'],
 ['CLE', 'Cleveland Indians'],
 ['COL', 'Colorado Rockies'],
 ['DET', 'Detroit Tigers'],
 ['FLA', 'Florida Marlins'],
 ['HOU', 'Houston Astros'],
 ['KAN', 'Kansas City Royals'],
 ['LAA', 'Anaheim Angels'],
 ['LAD', 'Los Angeles Dodgers'],
 ['MIL', 'Milwaukee Brewers'],
 ['MIN', 'Minnesota Twins'],
 ['NYM', 'New York Mets'],
 ['NYY', 'New York Yankees'],
 ['OAK', 'Oakland Athletics'],
 ['PHI', 'Philadelphia Phillies'],
 ['PIT', 'Pittsburgh Pirates'],
 ['SD', 'San Diego Padres'],
 ['SF', 'San Francisco Giants'],
 ['SEA', 'Seattle Mariners'],
 ['STL', 'St. Louis Cardinals'],
 ['TB', 'Tampa Bay Rays'],
 ['TEX', 'Texas Rangers'],
 ['TOR', 'Toronto Blue Jays'],
 ['WAS', 'Washington Nationals']]

In [347]:
lookup = {}
for row in xwalk_list3:
    lookup[row[0]] = row[1]

In [348]:
lookup

{'ARI': 'Arizona Diamondbacks',
 'ATL': 'Atlanta Braves',
 'BAL': 'Baltimore Orioles',
 'BOS': 'Boston Red Sox',
 'CHC': 'Chicago Cubs',
 'CHW': 'Chicago White Sox',
 'CIN': 'Cincinnati Reds',
 'CLE': 'Cleveland Indians',
 'COL': 'Colorado Rockies',
 'DET': 'Detroit Tigers',
 'FLA': 'Florida Marlins',
 'HOU': 'Houston Astros',
 'KAN': 'Kansas City Royals',
 'LAA': 'Anaheim Angels',
 'LAD': 'Los Angeles Dodgers',
 'MIL': 'Milwaukee Brewers',
 'MIN': 'Minnesota Twins',
 'NYM': 'New York Mets',
 'NYY': 'New York Yankees',
 'OAK': 'Oakland Athletics',
 'PHI': 'Philadelphia Phillies',
 'PIT': 'Pittsburgh Pirates',
 'SD': 'San Diego Padres',
 'SF': 'San Francisco Giants',
 'SEA': 'Seattle Mariners',
 'STL': 'St. Louis Cardinals',
 'TB': 'Tampa Bay Rays',
 'TEX': 'Texas Rangers',
 'TOR': 'Toronto Blue Jays',
 'WAS': 'Washington Nationals'}

In [357]:
lookup = {
    'ARI': 'Arizona Diamondbacks',
    'ATL': 'Atlanta Braves',
    'BAL': 'Baltimore Orioles',
    'BOS': 'Boston Red Sox',
    'CHC': 'Chicago Cubs',
    'CHW': 'Chicago White Sox',
    'CIN': 'Cincinnati Reds',
    'CLE': 'Cleveland Indians',
    'COL': 'Colorado Rockies',
    'DET': 'Detroit Tigers',
    'FLA': 'Florida Marlins',
    'HOU': 'Houston Astros',
    'KAN': 'Kansas City Royals',
    'LAA': 'Anaheim Angels',
    'LAD': 'Los Angeles Dodgers',
    'MIL': 'Milwaukee Brewers',
    'MIN': 'Minnesota Twins',
    'NYM': 'New York Mets',
    'NYY': 'New York Yankees',
    'OAK': 'Oakland Athletics',
    'PHI': 'Philadelphia Phillies',
    'PIT': 'Pittsburgh Pirates',
    'SDP': 'San Diego Padres',
    'SFG': 'San Francisco Giants',
    'SEA': 'Seattle Mariners',
    'STL': 'St. Louis Cardinals',
    'TBR': 'Tampa Bay Rays',
    'TEX': 'Texas Rangers',
    'TOR': 'Toronto Blue Jays',
    'WAS': 'Washington Nationals'
}

In [351]:
lookup

{'ARI': 'Arizona Diamondbacks',
 'ATL': 'Atlanta Braves',
 'BAL': 'Baltimore Orioles',
 'BOS': 'Boston Red Sox',
 'CHC': 'Chicago Cubs',
 'CHW': 'Chicago White Sox',
 'CIN': 'Cincinnati Reds',
 'CLE': 'Cleveland Indians',
 'COL': 'Colorado Rockies',
 'DET': 'Detroit Tigers',
 'FLA': 'Florida Marlins',
 'HOU': 'Houston Astros',
 'KAN': 'Kansas City Royals',
 'LAA': 'Anaheim Angels',
 'LAD': 'Los Angeles Dodgers',
 'MIL': 'Milwaukee Brewers',
 'MIN': 'Minnesota Twins',
 'NYM': 'New York Mets',
 'NYY': 'New York Yankees',
 'OAK': 'Oakland Athletics',
 'PHI': 'Philadelphia Phillies',
 'PIT': 'Pittsburgh Pirates',
 'SDP': 'San Diego Padres',
 'SFG': 'San Francisco Giants',
 'SEA': 'Seattle Mariners',
 'STL': 'St. Louis Cardinals',
 'TBR': 'Tampa Bay Rays',
 'TEX': 'Texas Rangers',
 'TOR': 'Toronto Blue Jays',
 'WAS': 'Washington Nationals'}

In [358]:
lookup1 = {k:{'full_name':v, 'alt_name':k} for k,v in lookup.items()}

In [360]:
lookup1

{'ARI': {'full_name': 'Arizona Diamondbacks', 'alt_name': 'ARI'},
 'ATL': {'full_name': 'Atlanta Braves', 'alt_name': 'ATL'},
 'BAL': {'full_name': 'Baltimore Orioles', 'alt_name': 'BAL'},
 'BOS': {'full_name': 'Boston Red Sox', 'alt_name': 'BOS'},
 'CHC': {'full_name': 'Chicago Cubs', 'alt_name': 'CHC'},
 'CHW': {'full_name': 'Chicago White Sox', 'alt_name': 'CHW'},
 'CIN': {'full_name': 'Cincinnati Reds', 'alt_name': 'CIN'},
 'CLE': {'full_name': 'Cleveland Indians', 'alt_name': 'CLE'},
 'COL': {'full_name': 'Colorado Rockies', 'alt_name': 'COL'},
 'DET': {'full_name': 'Detroit Tigers', 'alt_name': 'DET'},
 'FLA': {'full_name': 'Florida Marlins', 'alt_name': 'FLA'},
 'HOU': {'full_name': 'Houston Astros', 'alt_name': 'HOU'},
 'KAN': {'full_name': 'Kansas City Royals', 'alt_name': 'KAN'},
 'LAA': {'full_name': 'Anaheim Angels', 'alt_name': 'LAA'},
 'LAD': {'full_name': 'Los Angeles Dodgers', 'alt_name': 'LAD'},
 'MIL': {'full_name': 'Milwaukee Brewers', 'alt_name': 'MIL'},
 'MIN': {'full_name': 'Minnesota Twins', 'alt_name': 'MIN'},
 'NYM': {'full_name': 'New York Mets', 'alt_name': 'NYM'},
 'NYY': {'full_name': 'New York Yankees', 'alt_name': 'NYY'},
 'OAK': {'full_name': 'Oakland Athletics', 'alt_name': 'OAK'},
 'PHI': {'full_name': 'Philadelphia Phillies', 'alt_name': 'PHI'},
 'PIT': {'full_name': 'Pittsburgh Pirates', 'alt_name': 'PIT'},
 'SDP': {'full_name': 'San Diego Padres', 'alt_name': 'SDP'},
 'SFG': {'full_name': 'San Francisco Giants', 'alt_name': 'SFG'},
 'SEA': {'full_name': 'Seattle Mariners', 'alt_name': 'SEA'},
 'STL': {'full_name': 'St. Louis Cardinals', 'alt_name': 'STL'},
 'TBR': {'full_name': 'Tampa Bay Rays', 'alt_name': 'TBR'},
 'TEX': {'full_name': 'Texas Rangers', 'alt_name': 'TEX'},
 'TOR': {'full_name': 'Toronto Blue Jays', 'alt_name': 'TOR'},
 'WAS': {'full_name': 'Washington Nationals', 'alt_name': 'WAS'}}

In [354]:
lookup = {
    'ARI': {'full_name': 'Arizona Diamondbacks', 'alt_name': ''},
    'ATL': {'full_name': 'Atlanta Braves', 'alt_name': ''},
    'BAL': {'full_name': 'Baltimore Orioles', 'alt_name': ''},
    'BOS': {'full_name': 'Boston Red Sox', 'alt_name': ''},
    'CHC': {'full_name': 'Chicago Cubs', 'alt_name': ''},
    'CHW': {'full_name': 'Chicago White Sox', 'alt_name': ''},
    'CIN': {'full_name': 'Cincinnati Reds', 'alt_name': ''},
    'CLE': {'full_name': 'Cleveland Indians', 'alt_name': ''},
    'COL': {'full_name': 'Colorado Rockies', 'alt_name': ''},
    'DET': {'full_name': 'Detroit Tigers', 'alt_name': ''},
    'FLA': {'full_name': 'Florida Marlins', 'alt_name': ''},
    'HOU': {'full_name': 'Houston Astros', 'alt_name': ''},
    'KAN': {'full_name': 'Kansas City Royals', 'alt_name': ''},
    'LAA': {'full_name': 'Anaheim Angels', 'alt_name': ''},
    'LAD': {'full_name': 'Los Angeles Dodgers', 'alt_name': ''},
    'MIL': {'full_name': 'Milwaukee Brewers', 'alt_name': ''},
    'MIN': {'full_name': 'Minnesota Twins', 'alt_name': ''},
    'NYM': {'full_name': 'New York Mets', 'alt_name': ''},
    'NYY': {'full_name': 'New York Yankees', 'alt_name': ''},
    'OAK': {'full_name': 'Oakland Athletics', 'alt_name': ''},
    'PHI': {'full_name': 'Philadelphia Phillies', 'alt_name': ''},
    'PIT': {'full_name': 'Pittsburgh Pirates', 'alt_name': ''},
    'SDP': {'full_name': 'San Diego Padres', 'alt_name': 'SDN'},
    'SFG': {'full_name': 'San Francisco Giants', 'alt_name': ''},
    'SEA': {'full_name': 'Seattle Mariners', 'alt_name': ''},
    'STL': {'full_name': 'St. Louis Cardinals', 'alt_name': ''},
    'TBR': {'full_name': 'Tampa Bay Rays', 'alt_name': ''},
    'TEX': {'full_name': 'Texas Rangers', 'alt_name': ''},
    'TOR': {'full_name': 'Toronto Blue Jays', 'alt_name': ''},
    'WAS': {'full_name': 'Washington Nationals', 'alt_name': ''}
    }

In [361]:
url = 'https://www.baseball-reference.com/boxes/ARI/ARI201404010.shtml'
resp = requests.get(url=url)

In [362]:
resp

In [367]:
resp.headers

{'Date': 'Sun, 07 May 2023 22:28:56 GMT', 'Content-Type': 'text/html; charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Retry-After': '3449', 'X-Frame-Options': 'SAMEORIGIN', 'Referrer-Policy': 'same-origin', 'Cache-Control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'Expires': 'Thu, 01 Jan 1970 00:00:01 GMT', 'Set-Cookie': '__cf_bm=g.EZZXMkvEgBgsiqZU_9DgCux6wJ5Owb4rXbq6ascSM-1683498536-0-ATNt/DHn+HgZXTzx35i3A+57WqLqUWKlsHZv0rlYDhoZmIh/bQtQH67j/U+5VOkIiiGQ/EeVL9yweQTOu2BcpJ4=; path=/; expires=Sun, 07-May-23 22:58:56 GMT; domain=.baseball-reference.com; HttpOnly; Secure; SameSite=None', 'Vary': 'Accept-Encoding', 'Server': 'cloudflare', 'CF-RAY': '7c3ce61f6bdfcf9b-SJC'}

In [368]:
from pybaseball import statcast_single_game

In [414]:
data = statcast_single_game(380537)

In [415]:
data.columns.values

array(['pitch_type', 'game_date', 'release_speed', 'release_pos_x',
       'release_pos_z', 'player_name', 'batter', 'pitcher', 'events',
       'description', 'spin_dir', 'spin_rate_deprecated',
       'break_angle_deprecated', 'break_length_deprecated', 'zone', 'des',
       'game_type', 'stand', 'p_throws', 'home_team', 'away_team', 'type',
       'hit_location', 'bb_type', 'balls', 'strikes', 'game_year',
       'pfx_x', 'pfx_z', 'plate_x', 'plate_z', 'on_3b', 'on_2b', 'on_1b',
       'outs_when_up', 'inning', 'inning_topbot', 'hc_x', 'hc_y',
       'tfs_deprecated', 'tfs_zulu_deprecated', 'fielder_2', 'umpire',
       'sv_id', 'vx0', 'vy0', 'vz0', 'ax', 'ay', 'az', 'sz_top', 'sz_bot',
       'hit_distance_sc', 'launch_speed', 'launch_angle',
       'effective_speed', 'release_spin_rate', 'release_extension',
       'game_pk', 'pitcher.1', 'fielder_2.1', 'fielder_3', 'fielder_4',
       'fielder_5', 'fielder_6', 'fielder_7', 'fielder_8', 'fielder_9',
       'release_pos_y', 'estimated_ba_using_speedangle',
       'estimated_woba_using_speedangle', 'woba_value', 'woba_denom',
       'babip_value', 'iso_value', 'launch_speed_angle', 'at_bat_number',
       'pitch_number', 'pitch_name', 'home_score', 'away_score',
       'bat_score', 'fld_score', 'post_away_score', 'post_home_score',
       'post_bat_score', 'post_fld_score', 'if_fielding_alignment',
       'of_fielding_alignment', 'spin_axis', 'delta_home_win_exp',
       'delta_run_exp'], dtype=object)

In [408]:
import sqlalchemy
import psycopg2
from sqlalchemy import create_engine
from urllib.parse import quote_plus
import json
from typing import Generator

In [418]:
database_username = 'raguilar'
database_password = quote_plus("Lb$bYdu^2P%gv%D6cfqNJ7@aAhE&jT7r")
database_ip       = 'localhost'
database_name     = 'mlb_dw'

database_connection = sqlalchemy.create_engine('postgresql+psycopg2://{0}:{1}@{2}/{3}'.
                                               format(database_username, database_password, 
                                                      database_ip, database_name), pool_timeout = 28800, max_overflow = -1)
connection = database_connection.connect()
print("made connection")
try:
    data.to_sql('game_data', connection, if_exists='append')
except Exception as e:
    print(f"error: {e}")
    connection.close()
connection.close()

made connection

In [11]:
with open('./data/sched_2014.json', 'r') as infile:
    sched_2014 = infile.read()
    sched_2014_json = json.loads(sched_2014)

In [379]:
len(sched_2014_json['dates'])

210

In [401]:
def index_words_iter(text):
    if text:
        yield 0
    for index, letter in enumerate(text):
        if letter == ' ':
            yield index + 1

In [406]:
for i in index_words_iter(address):
    print(i)

0
5
11
15
21
27

In [407]:
sched_2014_json['dates'][0]['games'][0]['gamePk']

380537

In [9]:
def extract_games(schedule: json) -> Generator[dict, None, None]:
    for date in schedule['dates']:
        for game in date['games']:
            yield {'date':date['date'], 'gamePk':game['gamePk']}

In [12]:
ext_games_2014 = extract_games(sched_2014_json)

In [412]:
print(next(ext_games_2014))

{'date': '2014-03-22', 'gamePk': 380537}

In [13]:
for date in ext_games_2014:
    connection = database_connection.connect()
    print("made connection")
    try:
        data = statcast_single_game(date['gamePk'])
        data.to_sql('game_data', connection, if_exists='append')
        with open('./data/inserted_into_game_data.txt', 'a') as outfile:
            outfile.write(str(date['gamePk']))
    except Exception as e:
        print(f"error={e}, gamePk={date['gamePk']}")
        connection.close()
    connection.close()

made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
error='NoneType' object has no attribute 'to_sql', gamePk=396163
made connection
error='NoneType' object has no attribute 'to_sql', gamePk=396453
made connection
error='NoneType' object has no attribute 'to_sql', gamePk=396373
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
error='NoneType' object has no attribute 'to_sql', gamePk=396992
made connection
error='NoneType' object has no attribute 'to_sql', gamePk=396674
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
error='NoneType' object has no attribute 'to_sql', gamePk=385473
made connection
error='NoneType' object has no attribute 'to_sql', gamePk=396409
made connection
error='NoneType' object has no attribute 'to_sql', gamePk=383312
made connection
error='NoneType' object has no attribute 'to_sql', gamePk=395418
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection
made connection

KeyboardInterrupt:

In [32]:
import sqlalchemy
import psycopg2
from sqlalchemy import create_engine
from urllib.parse import quote_plus
import json
from typing import Generator
import requests
import re
import pandas as pd
import logging
import csv
import time
from pybaseball import statcast_single_game, statcast_pitcher, playerid_reverse_lookup

In [2]:
game_395716 = statcast_single_game(395716)

In [4]:
game_395716

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,...,fld_score,post_away_score,post_home_score,post_bat_score,post_fld_score,if_fielding_alignment,of_fielding_alignment,spin_axis,delta_home_win_exp,delta_run_exp
238,FF,2014-03-27,96.8,-1.82,5.49,"Van Slyke, Scott",475100,592135,field_out,hit_into_play,...,7,7,5,5,7,NaN,NaN,NaN,-0.044,NaN
247,SL,2014-03-27,85.7,-2.18,5.33,"Van Slyke, Scott",475100,592135,NaN,blocked_ball,...,7,7,5,5,7,NaN,NaN,NaN,0.000,NaN
255,FF,2014-03-27,96.0,-1.72,5.44,"Van Slyke, Scott",475100,592135,NaN,blocked_ball,...,7,7,5,5,7,NaN,NaN,NaN,0.000,NaN
267,SL,2014-03-27,85.0,-2.22,5.49,"Van Slyke, Scott",475100,592135,NaN,ball,...,7,7,5,5,7,NaN,NaN,NaN,0.000,NaN
275,SL,2014-03-27,84.8,-2.08,5.40,"Van Slyke, Scott",475100,592135,NaN,swinging_strike,...,7,7,5,5,7,NaN,NaN,NaN,0.000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
248,FF,2014-03-27,90.5,-1.23,5.97,"Trout, Mike",545361,425844,NaN,called_strike,...,0,0,0,0,0,NaN,NaN,NaN,0.000,NaN
256,FF,2014-03-27,92.3,-1.16,6.20,"Calhoun, Kole",594777,425844,field_out,hit_into_play,...,0,0,0,0,0,NaN,NaN,NaN,0.022,NaN
263,CU,2014-03-27,72.5,-1.40,6.32,"Calhoun, Kole",594777,425844,NaN,foul,...,0,0,0,0,0,NaN,NaN,NaN,0.000,NaN
279,CU,2014-03-27,71.8,-1.45,6.58,"Calhoun, Kole",594777,425844,NaN,ball,...,0,0,0,0,0,NaN,NaN,NaN,0.000,NaN
289,FF,2014-03-27,90.5,-1.51,5.95,"Calhoun, Kole",594777,425844,NaN,called_strike,...,0,0,0,0,0,NaN,NaN,NaN,0.000,NaN

In [5]:
database_username = 'raguilar'
database_password = quote_plus("Lb$bYdu^2P%gv%D6cfqNJ7@aAhE&jT7r")
database_ip       = 'localhost'
database_name     = 'mlb_dw'
database_connection = sqlalchemy.create_engine('postgresql+psycopg2://{0}:{1}@{2}/{3}'.
                                               format(database_username, database_password, 
                                                      database_ip, database_name), pool_timeout = 28800, max_overflow = -1)
connection = database_connection.connect()
game_395716.to_sql('game_data', connection, if_exists='append')
connection.close()

DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type double precision: "140327_221036"
LINE 1: ... 'Bot', 141.57, 152.61, NULL, NULL, 446208, NULL, '140327_22...
                                                             ^

[SQL: INSERT INTO game_data (index, pitch_type, game_date, release_speed, release_pos_x, release_pos_z, player_name, batter, pitcher, events, description, spin_dir, spin_rate_deprecated, break_angle_deprecated, break_length_deprecated, zone, des, game_type ... 564729 characters truncated ... _fielding_alignment__290)s, %(spin_axis__290)s, %(delta_home_win_exp__290)s, %(delta_run_exp__290)s)]
[parameters: {'ax__0': -6.346, 'delta_home_win_exp__0': -0.044, 'inning__0': 9, 'fielder_3__0': 543068, 'release_pos_z__0': 5.49, 'away_team__0': 'LAA', 'az__0': -11.871, 'spin_axis__0': None, 'ay__0': 31.195, 'vy0__0': -140.669, 'batter__0': 475100, 'sz_top__0': 3.58, 'home_score__0': 5, 'home_team__0': 'LAD', 'spin_rate_deprecated__0': None, 'pitcher__0': 592135, 'pitcher_1__0': 592135, 'game_pk__0': 395716, 'release_extension__0': None, 'launch_angle__0': None, 'hit_distance_sc__0': None, 'post_home_score__0': 5, 'stand__0': 'R', 'sv_id__0': '140327_221036', 'release_pos_y__0': 50, 'fielder_6__0': 502205, 'release_pos_x__0': -1.82, 'babip_value__0': 0.0, 'launch_speed__0': None, 'fielder_5__0': 456655, 'post_bat_score__0': 5, 'of_fielding_alignment__0': None, 'pitch_name__0': '4-Seam Fastball', 'woba_value__0': 0.0, 'post_fld_score__0': 7, 'bb_type__0': 'line_drive', 'inning_topbot__0': 'Bot', 'release_speed__0': 96.8, 'zone__0': 7, 'away_score__0': 7, 'type__0': 'X', 'on_3b__0': None, 'tfs_deprecated__0': None, 'effective_speed__0': None, 'woba_denom__0': None, 'game_year__0': 2014, 'estimated_ba_using_speedangle__0': None, 'fielder_8__0': 518577, 'pitch_type__0': 'FF', 'player_name__0': 'Van Slyke, Scott' ... 26963 parameters truncated ... 'effective_speed__290': None, 'woba_denom__290': None, 'game_year__290': 2014, 'estimated_ba_using_speedangle__290': None, 'fielder_8__290': 444843, 'pitch_type__290': 'FF', 'player_name__290': 'Calhoun, Kole', 'des__290': 'Kole Calhoun flies out to left fielder Carl Crawford.', 'iso_value__290': None, 'on_1b__290': None, 'vz0__290': -5.952, 'hc_y__290': None, 'post_away_score__290': 0, 'plate_x__290': -0.86, 'description__290': 'called_strike', 'fielder_4__290': 457759, 'p_throws__290': 'R', 'fielder_2_1__290': 454560, 'sz_bot__290': 1.53, 'spin_dir__290': None, 'at_bat_number__290': 1, 'hc_x__290': None, 'strikes__290': 0, 'pfx_x__290': -0.49, 'game_type__290': 'S', 'fld_score__290': 0, 'pitch_number__290': 1, 'events__290': None, 'game_date__290': datetime.datetime(2014, 3, 27, 0, 0), 'outs_when_up__290': 0, 'fielder_9__290': 624577, 'umpire__290': None, 'if_fielding_alignment__290': None, 'break_length_deprecated__290': None, 'on_2b__290': None, 'hit_location__290': None, 'bat_score__290': 0, 'launch_speed_angle__290': None, 'fielder_7__290': 408307, 'plate_z__290': 2.39, 'delta_run_exp__290': None, 'index__290': 289, 'break_angle_deprecated__290': None, 'pfx_z__290': 1.2, 'vx0__290': 2.899, 'fielder_2__290': 454560, 'tfs_zulu_deprecated__290': None, 'balls__290': 0, 'release_spin_rate__290': None, 'estimated_woba_using_speedangle__290': None}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)

In [7]:
[print(x) for x in game_395716.iloc[0]]

FF
2014-03-27 00:00:00
96.8
-1.82
5.49
Van Slyke, Scott
475100
592135
field_out
hit_into_play
nan
nan
nan
nan
7
Scott Van Slyke lines out to second baseman Taylor Lindsey.
S
R
R
LAD
LAA
X
4.0
line_drive
3
2
2014
-0.41
1.44
-0.59
2.01
nan
nan
408210.0
2
9
Bot
141.57
152.61
nan
nan
446208
nan
140327_221036
4.555
-140.669
-7.524
-6.346
31.195
-11.871
3.58
1.66
nan
nan
nan
nan
nan
nan
395716
592135
446208
543068
592506
456655
502205
543776
518577
543461
50
nan
nan
0.0
nan
0.0
0.0
nan
76
6
4-Seam Fastball
5
7
5
7
7
5
5
7
nan
nan
nan
-0.044
nan

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [8]:
game_395716.columns.values[43]

'sv_id'

In [14]:
len(ext_games_2014)

TypeError: object of type 'generator' has no len()

In [16]:
[print(x) for x in game_395716.columns.values]

pitch_type
game_date
release_speed
release_pos_x
release_pos_z
player_name
batter
pitcher
events
description
spin_dir
spin_rate_deprecated
break_angle_deprecated
break_length_deprecated
zone
des
game_type
stand
p_throws
home_team
away_team
type
hit_location
bb_type
balls
strikes
game_year
pfx_x
pfx_z
plate_x
plate_z
on_3b
on_2b
on_1b
outs_when_up
inning
inning_topbot
hc_x
hc_y
tfs_deprecated
tfs_zulu_deprecated
fielder_2
umpire
sv_id
vx0
vy0
vz0
ax
ay
az
sz_top
sz_bot
hit_distance_sc
launch_speed
launch_angle
effective_speed
release_spin_rate
release_extension
game_pk
pitcher.1
fielder_2.1
fielder_3
fielder_4
fielder_5
fielder_6
fielder_7
fielder_8
fielder_9
release_pos_y
estimated_ba_using_speedangle
estimated_woba_using_speedangle
woba_value
woba_denom
babip_value
iso_value
launch_speed_angle
at_bat_number
pitch_number
pitch_name
home_score
away_score
bat_score
fld_score
post_away_score
post_home_score
post_bat_score
post_fld_score
if_fielding_alignment
of_fielding_alignment
spin_axis
delta_home_win_exp
delta_run_exp

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [18]:
pitcher = statcast_pitcher(start_dt='2014-05-11', end_dt='2014-06-01', player_id=218596)

Gathering Player Data

In [21]:
pitcher['bb_type']

0              NaN
1              NaN
2              NaN
3              NaN
4              NaN
          ...
334            NaN
335            NaN
336            NaN
337    ground_ball
338            NaN
Name: bb_type, Length: 339, dtype: object

In [20]:
[print(x) for x in pitcher.columns.values]

pitch_type
game_date
release_speed
release_pos_x
release_pos_z
player_name
batter
pitcher
events
description
spin_dir
spin_rate_deprecated
break_angle_deprecated
break_length_deprecated
zone
des
game_type
stand
p_throws
home_team
away_team
type
hit_location
bb_type
balls
strikes
game_year
pfx_x
pfx_z
plate_x
plate_z
on_3b
on_2b
on_1b
outs_when_up
inning
inning_topbot
hc_x
hc_y
tfs_deprecated
tfs_zulu_deprecated
fielder_2
umpire
sv_id
vx0
vy0
vz0
ax
ay
az
sz_top
sz_bot
hit_distance_sc
launch_speed
launch_angle
effective_speed
release_spin_rate
release_extension
game_pk
pitcher.1
fielder_2.1
fielder_3
fielder_4
fielder_5
fielder_6
fielder_7
fielder_8
fielder_9
release_pos_y
estimated_ba_using_speedangle
estimated_woba_using_speedangle
woba_value
woba_denom
babip_value
iso_value
launch_speed_angle
at_bat_number
pitch_number
pitch_name
home_score
away_score
bat_score
fld_score
post_away_score
post_home_score
post_bat_score
post_fld_score
if_fielding_alignment
of_fielding_alignment
spin_axis
delta_home_win_exp
delta_run_exp

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [22]:
pitcher

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,...,fld_score,post_away_score,post_home_score,post_bat_score,post_fld_score,if_fielding_alignment,of_fielding_alignment,spin_axis,delta_home_win_exp,delta_run_exp
0,SI,2014-06-01,90.4,-1.04,5.20,"Hudson, Tim",407885,218596,strikeout,called_strike,...,8,8,0,0,8,NaN,NaN,NaN,0.000,-0.106
1,FC,2014-06-01,85.4,-1.01,4.94,"Hudson, Tim",407885,218596,NaN,ball,...,8,8,0,0,8,NaN,NaN,NaN,0.000,0.030
2,SI,2014-06-01,89.4,-1.14,5.21,"Hudson, Tim",407885,218596,NaN,foul,...,8,8,0,0,8,NaN,NaN,NaN,0.000,0.000
3,FC,2014-06-01,84.3,-1.11,4.92,"Hudson, Tim",407885,218596,NaN,ball,...,8,8,0,0,8,NaN,NaN,NaN,0.000,0.015
4,SI,2014-06-01,90.0,-0.98,5.10,"Hudson, Tim",407885,218596,NaN,foul,...,8,8,0,0,8,NaN,NaN,NaN,0.000,-0.018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334,FC,2014-05-11,84.9,-1.20,5.10,"Hudson, Tim",624577,218596,NaN,ball,...,1,1,0,0,1,NaN,NaN,NaN,0.000,0.081
335,SI,2014-05-11,90.9,-1.22,5.22,"Hudson, Tim",624577,218596,NaN,ball,...,1,1,0,0,1,NaN,NaN,NaN,0.000,0.038
336,SI,2014-05-11,91.5,-1.11,5.16,"Hudson, Tim",624577,218596,NaN,ball,...,1,1,0,0,1,NaN,NaN,NaN,0.000,0.022
337,CU,2014-05-11,76.8,-1.23,5.45,"Hudson, Tim",543829,218596,field_out,hit_into_play,...,1,1,0,0,1,NaN,NaN,NaN,-0.023,-0.190
338,SI,2014-05-11,90.4,-1.14,5.07,"Hudson, Tim",543829,218596,NaN,called_strike,...,1,1,0,0,1,NaN,NaN,NaN,0.000,-0.031

In [25]:
pitcher_458681 = statcast_pitcher(start_dt='2014-05-16', end_dt='2014-05-16', player_id=458681)

Gathering Player Data

In [27]:
pitcher_458681.sum

<bound method NDFrame._add_numeric_operations.<locals>.sum of     pitch_type   game_date  release_speed  release_pos_x  release_pos_z
0           FF  2014-05-16           93.4          -2.26           5.29  \
1           SI  2014-05-16           93.0          -2.38           5.38
2           SI  2014-05-16           93.0          -2.19           5.18
3           FF  2014-05-16           92.6          -2.34           5.30
4           CU  2014-05-16           78.9          -2.23           5.53
..         ...         ...            ...            ...            ...
105         FF  2014-05-16           92.7          -1.90           5.72
106         FF  2014-05-16           91.8          -1.91           5.75
107         FF  2014-05-16           92.3          -2.18           5.71
108         FF  2014-05-16           92.0          -2.20           5.47
109         FF  2014-05-16           91.0          -2.15           5.42

     player_name  batter  pitcher     events      description  ...  fld_score
0    Lynn, Lance  518792   458681  field_out    hit_into_play  ...          5  \
1    Lynn, Lance  518792   458681        NaN    called_strike  ...          5
2    Lynn, Lance  543629   458681  field_out    hit_into_play  ...          5
3    Lynn, Lance  543629   458681        NaN    called_strike  ...          5
4    Lynn, Lance  457788   458681  field_out    hit_into_play  ...          5
..           ...     ...      ...        ...              ...  ...        ...
105  Lynn, Lance  457708   458681        NaN  swinging_strike  ...          0
106  Lynn, Lance  457708   458681        NaN             ball  ...          0
107  Lynn, Lance  457708   458681        NaN    called_strike  ...          0
108  Lynn, Lance  518792   458681     single    hit_into_play  ...          0
109  Lynn, Lance  518792   458681        NaN             ball  ...          0

     post_away_score  post_home_score  post_bat_score  post_fld_score
0                  2                5               2               5  \
1                  2                5               2               5
2                  2                5               2               5
3                  2                5               2               5
4                  2                5               2               5
..               ...              ...             ...             ...
105                0                0               0               0
106                0                0               0               0
107                0                0               0               0
108                0                0               0               0
109                0                0               0               0

    if_fielding_alignment of_fielding_alignment spin_axis delta_home_win_exp
0                     NaN                   NaN       NaN              0.008  \
1                     NaN                   NaN       NaN              0.000
2                     NaN                   NaN       NaN              0.014
3                     NaN                   NaN       NaN              0.000
4                     NaN                   NaN       NaN              0.022
..                    ...                   ...       ...                ...
105                   NaN                   NaN       NaN              0.000
106                   NaN                   NaN       NaN              0.000
107                   NaN                   NaN       NaN              0.000
108                   NaN                   NaN       NaN             -0.036
109                   NaN                   NaN       NaN              0.000

    delta_run_exp
0          -0.071
1          -0.014
2          -0.128
3          -0.021
4          -0.190
..            ...
105        -0.087
106         0.040
107        -0.045
108         0.351
109         0.031

[110 rows x 92 columns]>

In [28]:
with open('./data/pitcher_subset.csv', 'r') as infile:
    pitcher_subset = infile.read()

In [30]:
pitcher_subset = pitcher_subset.split('\n')

In [44]:
pitcher_subset

['112526',
 '115629',
 '124604',
 '136600',
 '150035',
 '150116',
 '150119',
 '150188',
 '150274',
 '150359',
 '218596',
 '275933',
 '276351',
 '276520',
 '276542',
 '277417',
 '279571',
 '279824',
 '282332',
 '283166',
 '285064',
 '285079',
 '329092',
 '346793',
 '346797',
 '346798',
 '346847',
 '400089',
 '407193',
 '407793',
 '407816',
 '407819',
 '407822',
 '407825',
 '407842',
 '407845',
 '407853',
 '407878',
 '407890',
 '407908',
 '407911',
 '408061',
 '408241',
 '421685',
 '424144',
 '424324',
 '425386',
 '425426',
 '425514',
 '425532',
 '425626',
 '425657',
 '425786',
 '425794',
 '425826',
 '425840',
 '425844',
 '425856',
 '425861',
 '429717',
 '429719',
 '429722',
 '429781',
 '430580',
 '430588',
 '430589',
 '430599',
 '430606',
 '430613',
 '430630',
 '430641',
 '430661',
 '430673',
 '430683',
 '430904',
 '430911',
 '430912',
 '430935',
 '431148',
 '431162',
 '432934',
 '433579',
 '433584',
 '433585',
 '433586',
 '433587',
 '433589',
 '434181',
 '434378',
 '434442',
 '434538',
 '434578',
 '434622',
 '434628',
 '434637',
 '434641',
 '434643',
 '434663',
 '434665',
 '434671',
 '434718',
 '434884',
 '435043',
 '435044',
 '435045',
 '435221',
 '444436',
 '444468',
 '444520',
 '444857',
 '445060',
 '445090',
 '445153',
 '445156',
 '445163',
 '445170',
 '445197',
 '445213',
 '445216',
 '445276',
 '445590',
 '445612',
 '445926',
 '445968',
 '446099',
 '446185',
 '446264',
 '446321',
 '446367',
 '446372',
 '446399',
 '446488',
 '446641',
 '446899',
 '447744',
 '447755',
 '448159',
 '448167',
 '448178',
 '448281',
 '448306',
 '448609',
 '448614',
 '448660',
 '449079',
 '449097',
 '449104',
 '449170',
 '449173',
 '450172',
 '450203',
 '450212',
 '450275',
 '450282',
 '450306',
 '450308',
 '450351',
 '450729',
 '451084',
 '451085',
 '451216',
 '451584',
 '451585',
 '451596',
 '451628',
 '451661',
 '451773',
 '451775',
 '451783',
 '451990',
 '452657',
 '452666',
 '452718',
 '453156',
 '453172',
 '453173',
 '453178',
 '453184',
 '453192',
 '453198',
 '453222',
 '453241',
 '453249',
 '453264',
 '453265',
 '453284',
 '453286',
 '453307',
 '453311',
 '453329',
 '453343',
 '453344',
 '453402',
 '453515',
 '453562',
 '453646',
 '454537',
 '454974',
 '455009',
 '455077',
 '455117',
 '455119',
 '455374',
 '455994',
 '456034',
 '456043',
 '456045',
 '456051',
 '456068',
 '456379',
 '456387',
 '456496',
 '456501',
 '456696',
 '456701',
 '456776',
 '457117',
 '457425',
 '457429',
 '457435',
 '457448',
 '457566',
 '457580',
 '457707',
 '457711',
 '457744',
 '457768',
 '457778',
 '457779',
 '457918',
 '457935',
 '458006',
 '458584',
 '458589',
 '458676',
 '458677',
 '458681',
 '458708',
 '458709',
 '458713',
 '458730',
 '458919',
 '458950',
 '459420',
 '459429',
 '459932',
 '459939',
 '459967',
 '459987',
 '460008',
 '460044',
 '460059',
 '460077',
 '460092',
 '460105',
 '460156',
 '460283',
 '460370',
 '460701',
 '461325',
 '461791',
 '461829',
 '461833',
 '461848',
 '461856',
 '461872',
 '462102',
 '462136',
 '462382',
 '462515',
 '462945',
 '462956',
 '462985',
 '463037',
 '464416',
 '465629',
 '465657',
 '465679',
 '465691',
 '466454',
 '466918',
 '466948',
 '466961',
 '467008',
 '467094',
 '467100',
 '468396',
 '468504',
 '468528',
 '469134',
 '469159',
 '469686',
 '471822',
 '471896',
 '471911',
 '472551',
 '472610',
 '472906',
 '473265',
 '473646',
 '474029',
 '474039',
 '474284',
 '474463',
 '474521',
 '474599',
 '475054',
 '475115',
 '475243',
 '475416',
 '475479',
 '475857',
 '476123',
 '476205',
 '476270',
 '476454',
 '476570',
 '476589',
 '476595',
 '477003',
 '477132',
 '477229',
 '477409',
 '477557',
 '477569',
 '477584',
 '487019',
 '488674',
 '488748',
 '488768',
 '488786',
 '488787',
 '488846',
 '488984',
 '489002',
 '489052',
 '489056',
 '489058',
 '489119',
 '489189',
 '489197',
 '489265',
 '489292',
 '489294',
 '489295',
 '489334',
 '490063',
 '490313',
 '491159',
 '491646',
 '491703',
 '491708',
 '493133',
 '493137',
 '493157',
 '493159',
 '493160',
 '493337',
 '493603',
 '493649',
 '499107',
 '500721',
 '500765',
 '500773',
 '500779',
 '500882',
 '500903',
 '501227',
 '501381',
 '501529',
 '501593',
 '501625',
 '501627',
 '501645',
 '501679',
 '501697',
 '501789',
 '501822',
 '501852',
 '501925',
 '501955',
 '501957',
 '501985',
 '501989',
 '502004',
 '502011',
 '502026',
 '502028',
 '502032',
 '502042',
 '502043',
 '502046',
 '502083',
 '502085',
 '502087',
 '502130',
 '502139',
 '502154',
 '502171',
 '502188',
 '502190',
 '502195',
 '502202',
 '502211',
 '502239',
 '502260',
 '502272',
 '502281',
 '502304',
 '502327',
 '502371',
 '502381',
 '502457',
 '502522',
 '502578',
 '502593',
 '502624',
 '502748',
 '503285',
 '503449',
 '504083',
 '504186',
 '504379',
 '506433',
 '506648',
 '506693',
 '514639',
 '514980',
 '515052',
 '516589',
 '516668',
 '516684',
 '516769',
 '516935',
 '516969',
 '517008',
 '517014',
 '517414',
 '517593',
 '518418',
 '518420',
 '518444',
 '518452',
 '518493',
 '518516',
 '518526',
 '518533',
 '518553',
 '518560',
 '518567',
 '518603',
 '518614',
 '518617',
 '518633',
 '518693',
 '518703',
 '518715',
 '518716',
 '518748',
 '518809',
 '518813',
 '518818',
 '518854',
 '518858',
 '518863',
 '518875',
 '518876',
 '518886',
 '518898',
 '518927',
 '518961',
 '519003',
 '519008',
 '519043',
 '519048',
 '519049',
 '519085',
 '519096',
 '519141',
 '519144',
 '519145',
 '519151',
 '519166',
 '519175',
 '519229',
 '519240',
 '519242',
 '519267',
 '519293',
 '519322',
 '519344',
 '519357',
 '519393',
 '519437',
 '519443',
 '519455',
 '520980',
 '521055',
 '523260',
 '523848',
 '525768',
 '527048',
 '527054',
 '527055',
 '533167',
 '534576',
 '534812',
 '539438',
 '541640',
 '542316',
 '542585',
 '542609',
 '542674',
 '542883',
 '542907',
 '542910',
 '542914',
 '542924',
 '542960',
 '543017',
 '543022',
 '543023',
 '543037',
 '543054',
 '543070',
 '543101',
 '543118',
 '543135',
 '543144',
 '543155',
 '543174',
 '543243',
 '543258',
 '543272',
 '543278',
 '543331',
 '543351',
 '543359',
 '543408',
 '543409',
 '543456',
 '543475',
 '543483',
 '543488',
 '543493',
 '543506',
 '543508',
 '543520',
 '543521',
 '543548',
 '543606',
 '543643',
 '543698',
 '543699',
 '543725',
 '543726',
 '543734',
 '543758',
 '543766',
 '543779',
 '543856',
 '543859',
 '543883',
 '543900',
 '543901',
 '543903',
 '543942',
 '543950',
 '544725',
 '544726',
 '544727',
 '544759',
 '544928',
 '544931',
 '544993',
 '545117',
 '545333',
 '545346',
 '545362',
 '545363',
 '545989',
 '547179',
 '547348',
 '547749',
 '547874',
 '547888',
 '547943',
 '547973',
 '552673',
 '554234',
 '554430',
 '554432',
 '570233',
 '570649',
 '571446',
 '571476',
 '571511',
 '571521',
 '571527',
 '571561',
 '571625',
 '571656',
 '571670',
 '571735',
 '571762',
 '571786',
 '571800',
 '571871',
 '571876',
 '571882',
 '571893',
 '571900',
 '571901',
 '571946',
 '571993',
 '572017',
 '572020',
 '572064',
 '572070',
 '572082',
 '572089',
 '572096',
 '572140',
 '572166',
 '572168',
 '572193',
 '572230',
 '572362',
 '572403',
 '572713',
 '572751',
 '572799',
 '572810',
 '572827',
 '572831',
 '572888',
 '572934',
 '572971',
 '573046',
 '573064',
 '573109',
 '573127',
 '573185',
 '573186',
 '573204',
 '576828',
 '591732',
 '592102',
 '592127',
 '592135',
 '592181',
 '592238',
 '592244',
 '592314',
 '592332',
 '592422',
 '592454',
 '592473',
 '592527',
 '592602',
 '592612',
 '592662',
 '592665',
 '592677',
 '592717',
 '592741',
 '592767',
 '592804',
 '592811',
 '592869',
 '593372',
 '593576',
 '594742',
 '594762',
 '594772',
 '594792',
 '594798',
 '594867',
 '594987',
 '595014',
 '595032',
 '595307',
 '595340',
 '598573',
 '599819',
 '599899',
 '605156',
 '605169',
 '605200',
 '605218',
 '605228',
 '605304',
 '605359',
 '605376',
 '605452',
 '605476',
 '605538',
 '605541',
 '606160',
 '606203',
 '606273',
 '606296',
 '607259',
 '607359',
 '607373',
 '607374',
 '607405',
 '607431',
 '607646',
 '607665',
 '607718',
 '608096',
 '608349',
 '608371',
 '608379',
 '608678',
 '612672',
 '619854',
 '621408',
 '621962',
 '622072',
 '623406',
 '623430',
 '623913',
 '623923',
 '624586',
 '633831',
 '634324',
 '641490',
 '641627',
 '643617',
 '648737',
 '652998',
 '']

In [46]:
pitcher_subset = [a for a in pitcher_subset if a != '']
pitcher_subset_ints = [int(x) for x in pitcher_subset]

In [47]:
pitcher_names = playerid_reverse_lookup(pitcher_subset_ints)

In [48]:
pitcher_names

,name_last,name_first,key_mlbam,key_retro,key_bbref,key_fangraphs,mlb_played_first,mlb_played_last
0,sadler,casey,594987,sadlc002,sadleca02,11209,2014.0,2021.0
1,sipp,tony,448609,sippt001,sippto01,8280,2009.0,2019.0
2,vogelsong,ryan,285064,voger001,vogelry01,1011,2000.0,2016.0
3,petricka,jake,502593,petrj001,petrija01,10534,2013.0,2021.0
4,neris,hector,593576,nerih001,nerishe01,11804,2014.0,2023.0
...,...,...,...,...,...,...,...,...
649,straily,dan,573185,strad003,straida01,9460,2012.0,2019.0
650,choate,randy,329092,choar001,choatra01,813,2000.0,2015.0
651,furbush,charlie,518703,furbc001,furbuch01,1370,2011.0,2015.0
652,volquez,edinson,450172,volqe001,volqued01,3990,2005.0,2020.0
653,hawkins,latroy,115629,hawkl001,hawkila01,729,1995.0,2015.0

In [54]:
pitcher_last_names = list(pitcher_names['name_last'])
pitcher_first_names = list(pitcher_names['name_first'])
bb_refs = pitcher_names['key_bbref']

In [64]:
xwalk_keys = pitcher_names[['key_mlbam', 'key_bbref']]

In [65]:
xwalk_keys

     key_mlbam  key_bbref
0       594987  sadleca02
1       448609   sippto01
2       285064  vogelry01
3       502593  petrija01
4       593576  nerishe01
..         ...        ...
649     573185  straida01
650     329092  choatra01
651     518703  furbuch01
652     450172  volqued01
653     115629  hawkila01

[654 rows x 2 columns]

In [66]:
database_username = 'raguilar'
database_password = quote_plus("Lb$bYdu^2P%gv%D6cfqNJ7@aAhE&jT7r")
database_ip       = 'localhost'
database_name     = 'mlb_dw'

database_connection = sqlalchemy.create_engine('postgresql+psycopg2://{0}:{1}@{2}/{3}'.
                                               format(database_username, database_password, 
                                                      database_ip, database_name), pool_timeout = 28800, max_overflow = -1)
connection = database_connection.connect()
print("made connection")
try:
    #data.to_sql('game_data', connection, if_exists='append')
    xwalk_keys.to_sql('xwalk_keys', connection, if_exists='append')
except Exception as e:
    print(f"error: {e}")
    connection.close()
connection.close()

made connection

In [69]:
df = pd.read_csv('./data/aggregate_stats_v3.csv')
df = df.drop(['Unnamed: 0'], axis = 1)
#df = df.drop(['Unnamed: 0.1'], axis = 1)
df.head()

,index,Name,Name_formatted,Tm,BA,BABIP,BIP,Games_played_to_date,ISO,LA_avg,...,X3B,HR,RBI,BB,SO,WPA,RE24,aLI,BOP,Pos.Summary
0,0,Travis d'Arnaud,"d'Arnaud, Travis",NaN,0.0,0.0,0.33333,1,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Travis d'Arnaud,"d'Arnaud, Travis",NYM,0.0,0.0,0.50000,2,0.0,NaN,...,0.0,0.0,0.0,1.0,2.0,-0.037,-0.425,0.870,7.0,C
2,2,Travis d'Arnaud,"d'Arnaud, Travis",NaN,0.0,0.0,0.44444,3,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Travis d'Arnaud,"d'Arnaud, Travis",NaN,0.0,0.0,0.50000,4,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Travis d'Arnaud,"d'Arnaud, Travis",NYM,0.0,0.0,0.60000,5,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.066,0.277,0.638,7.0,C

In [70]:
connection = database_connection.connect()
print("made connection")
try:
    #data.to_sql('game_data', connection, if_exists='append')
    df.to_sql('aggregate_stas_v3', connection, if_exists='append')
except Exception as e:
    print(f"error: {e}")
    connection.close()
connection.close()

made connection